package com.surf.graph.rexster

import com.surf.graph._

trait RexsterGraphModule extends GraphModule
with GraphAPIModuleImpl
with GraphQueryModuleImpl
with GraphMutationModuleImpl
with GraphSystemModuleImpl
with GraphBaseModuleImpl
with GraphQueryExecutionContext
with StandardExecutionContext
with RexsterRawGraph